heartbeat.monitors:
  - type: http
    name: kibana
    schedule: "@every 10s"
    hosts:
      - http://kibana:5601
  - type: http
    name: grafana
    schedule: "@every 10s"
    hosts:
      - http://grafana:3100
  - type: http
    name: prometheus
    schedule: "@every 10s"
    hosts:
      - http://prometheus:9090
  - type: http
    name: elasticsearch
    schedule: "@every 10s"
    username: "${ESUN_HEARTBEAT}"
    password: "${ESPW_HEARTBEAT}"
    hosts:
      - http://elasticsearch:9200
  - type: http
    name: onuser
    schedule: "@every 10s"
    hosts:
      - http://onuser:1234
  - type: http
    name: metricbeat
    schedule: "@every 10s"
    hosts:
      - http://metricbeat:5065
  - type: http
    name: filebeat
    schedule: "@every 10s"
    hosts:
      - http://filebeat:5066
  - type: http
    name: heartbeat
    schedule: "@every 10s"
    hosts:
      - http://heartbeat:5067
  - type: http
    name: staging paymentplus
    schedule: "@every 10s"
    hosts:
      - http://paymentplus.heroapp.dev:80
  - type: http
    name: production paymentplus
    schedule: "@every 10s"
    hosts:
      - http://pttep.users.heroapp.dev:80
  - type: icmp
    schedule: "@every 10s"
    hosts:
      - elasticsearch
      - kibana
      - prometheus
      - grafana
      - onuser

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "${ESUN_HEARTBEAT}"
  password: "${ESPW_HEARTBEAT}"

setup:
  dashboards:
    enabled: false
  kibana:
    host: "kibana:5601"
    username: "${ESUN_HEARTBEAT}"
    password: "${ESPW_HEARTBEAT}"

http:
  enabled: true
  host: 0.0.0.0
  port: 5067

monitoring:
  enabled: false
