version: "3.7"

volumes:
  logging:

services:
  elasticsearch-exporter:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/elasticsearch-exporter:latest
    command:
      - "--es.uri=http://remote_monitoring_user:hHfIHSeboCNeemqkOumz@elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "3503:9114"
  online-user:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/onuser:latest
    volumes:
      - logging:/var/log
    ports:
      - "3501:1234"
  prometheus:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/prometheus:latest
    volumes:
      - ./prometheus/data:/prometheus
      - logging:/var/log
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
    ports:
      - "3200:9090"
  grafana:
    image: gcr.io/the-tokenizer-268111/grafana:latest
    volumes:
      - ./grafana/data:/var/lib/grafana
      - logging:/var/log
    depends_on:
      - prometheus
    environment:
      GF_SERVER_HTTP_PORT: "3100"
      GF_SERVER_ROOT_URL: "http://34.69.181.155:3100"
    ports:
      - "3100:3100"
  elasticsearch:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/elasticsearch:latest
    volumes:
      - ./elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - logging:/var/log
    configs:
      - source: elasticsearch_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        uid: '1000'
        gid: '1000'
        mode: 0440
    environment:
      discovery.type: "single-node"
    ports:
      - "3201:9200"
      - "3202:9300"
  filebeat:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/filebeat:latest
    user: root
    environment:
      ESPW_FILEBEAT: "3mEAdNEcqprff2VCwCHG"
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - logging:/var/log
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
        uid: '0'
        gid: '0'
        mode: 0440
  metricbeat:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/metricbeat:latest
    user: root
    environment:
      ESPW_METRICBEAT: "YP4IDo3cZ2NNxqGRUv0I"
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - logging:/var/log
    configs:
      - source: metricbeat_config
        target: /usr/share/metricbeat/metricbeat.yml
        uid: '0'
        gid: '0'
        mode: 0440
  kibana:
    image: gcr.io/the-tokenizer-268111/kibana:latest
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - logging:/var/log
    environment:
      ESPW_KIBANA: "mYw11SpuBafbxnyGsv5b"
    depends_on:
      - elasticsearch
    ports:
      - "3101:5601"

configs:
  prometheus_config:
    file: ./prometheus/prometheus.yml
  elasticsearch_config:
    file: ./elasticsearch/elasticsearch.yml
  filebeat_config:
    file: ./filebeat.yml
  mtricbeat_config:
    file: ./metricbeat.yml
  kibana_config:
    file: ./kibana/kibana.yml
