version: "3"

volumes:
  logging:

services:
  node-exporter:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/node-exporter:latest
    volumes:
      - logging:/var/log
    ports:
      - "3502:9100"
  elasticsearch-exporter:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/elasticsearch-exporter:latest
    command:
      - "--es.uri=http://remote_monitoring_user:3LO2DgD6LWlEsHhu2VPm@elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - "3503:9114"
  online-user:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/onuser:latest
    volumes:
      - logging:/var/log
    ports:
      - "3501:1234"
  prometheus:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/prometheus:latest
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
      - logging:/var/log
    ports:
      - "3200:9090"
  grafana:
    image: gcr.io/the-tokenizer-268111/grafana:latest
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana
      - logging:/var/log
    depends_on:
      - prometheus
    environment:
      GF_SERVER_HTTP_PORT: "3100"
      GF_SERVER_ROOT_URL: "http://34.69.181.155:3100"
    ports:
      - "3100:3100"
  filebeat:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/filebeat:latest
    user: root
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - logging:/var/log
  metricbeat:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/metricbeat:latest
    user: root
    environment: 
      ESPW_BEAT: YP4IDo3cZ2NNxqGRUv0I
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - logging:/var/log
  logstash:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/logstash:latest
    environment: 
      ESPW_LOGSTASH: ""
      ESPW_LOGSTASH_INTERNAL: ""
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/data:/usr/share/logstash/data
      - logging:/var/log
    depends_on:
      - elasticsearch
    ports:
      - "3800:9600"
      - "3801:5044"
  elasticsearch:
    restart: on-failure
    image: gcr.io/the-tokenizer-268111/elasticsearch:latest
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      - ./elasticsearch/elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - logging:/var/log
    environment:
      discovery.type: "single-node"
    ports:
      - "3201:9200"
      - "3202:9300"
  kibana:
    image: gcr.io/the-tokenizer-268111/kibana:latest
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - logging:/var/log
    environment: 
      ESPW_KIBANA: ""
    depends_on:
      - elasticsearch
    ports:
      - "3101:5601"
