metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_cloud_metadata: ~

metricbeat.modules:
- module: docker
  enabled: true
  period: 10s
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "metricbeat_internal"
  password: "${ESPW_METRICBEAT}"

setup.kibana:
  host: "kibana:5601"
  username: "metricbeat_internal"
  password: "${ESPW_METRICBEAT}"