FROM docker.elastic.co/kibana/kibana:7.6.0

# NOT WORKING: kibana v7.6.0 is not support yet: https://github.com/pjhampton/kibana-prometheus-exporter/issues/135

RUN bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.6.0/kibana-prometheus-exporter-7.6.0.zip