FROM docker.elastic.co/kibana/kibana:7.6.0

# Deprecate: get kibana metric from metricbeat instead

RUN bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.6.0/kibana-prometheus-exporter-7.6.0.zip