global:
  external_labels:
    monitor: production
  scrape_interval: 30s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3100"
  - job_name: onuser
    static_configs:
      - targets:
          - "onuser:1234"
