global:
  external_labels:
    monitor: production
  scrape_interval: 30s
  scrape_timeout: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3100"
  - job_name: node-exporter
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: online-user
    static_configs:
      - targets:
          - "online-user:1234"
  - job_name: elasticsearch
    static_configs:
      - targets:
          - "elasticsearch-exporter:9114"
  - job_name: kibana
    metrics_path: "/_prometheus/metrics"
    static_configs:
      - targets:
          - "kibana:5601"
