metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

metricbeat.modules:
  - module: system
    enabled: true
    period: 10s
    metricsets:
      - cpu # CPU usage
      - load # CPU load averages
      - memory # Memory usage
      - network # Network IO
      - process # Per process metrics
      - process_summary # Process summary
      - uptime # System Uptime
      - socket_summary # Socket summary
      - core # Per CPU core usage
      - diskio # Disk IO
      - filesystem # File system usage for each mountpoint
      - fsstat # File system summary metrics
      - socket # Sockets and connection info (linux only)
      # - service # systemd service information
    processes: [".*"]
    # Configure the metric types that are included by these metricsets.
    cpu.metrics: ["percentages", "normalized_percentages"] # The other available option is ticks.
    core.metrics: ["percentages"] # The other available option is ticks.
    process.cgroups.enabled: true
  - module: docker
    enabled: true
    period: 10s
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
  - module: beat
    enabled: true
    xpack.enabled: false # Set to true to send data collected by module to X-Pack Monitoring instead of metricbeat-* indices.
    period: 10s
    metricsets:
      - stats
      - state
    username: "${ESUN_MONITOR}"
    password: "${ESPW_MONITOR}"
    hosts: ["http://filebeat:5066", "http://heartbeat:5067"]
  - module: elasticsearch
    enabled: true
    xpack.enabled: false
    period: 10s
    metricsets:
      - cluster_stats
      - node
      - node_stats
      - index
      - index_recovery
      - index_summary
      - shard
      - pending_tasks
    hosts: ["http://elasticsearch:9200"]
    username: "${ESUN_METRICBEAT}"
    password: "${ESPW_METRICBEAT}"
  - module: kibana
    enabled: true
    xpack.enabled: false
    period: 10s
    metricsets:
      - status
    hosts: ["http://kibana:5601"]
    basepath: ""
  - module: prometheus
    enabled: true
    period: 10s
    hosts: ["http://prometheus:9090"]
    metrics_path: /metrics

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "${ESUN_METRICBEAT}"
  password: "${ESPW_METRICBEAT}"

setup:
  dashboards:
    enabled: true
  kibana:
    host: "kibana:5601"
    username: "${ESUN_HEARTBEAT}"
    password: "${ESPW_HEARTBEAT}"

http:
  enabled: true
  port: 5065

monitoring:
  enabled: false
